sudo: required
dist: xenial

services:
  - docker

install:
  - docker build -t plaas_testing -f Dockerfile.testing .

script:
  - docker run plaas_testing

after_success:
  - docker run -e CODECOV_TOKEN plaas_testing 'codecov'