sudo: required
dist: xenial

services:
  - docker

install:
  - docker build -e CODECOV_TOKEN -t plaas_testing -f Dockerfile.testing .

script:
  - docker run plaas_testing

after_success:
  - docker run plaas_testing 'codecov'