language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
script: 'pipenv run pytest tests'
after_success:
  - 'codecov'